version: "3.8"

services:
  postgres:
    container_name: ts-db
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=ts
    ports:
      - "5434:5432"
    networks:
      - backend
    volumes:
      - postgres-data:/var/lib/postgresql/data

  ts:
    container_name: ts-backend
    image: quay.io/yugabyte/yb-troubleshooting-service
    environment:
      - DB_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_PORT=5434
      - DB_HOST=host.docker.internal
      - DB_NAME=ts
    ports:
      - "8080:8080"
    links:
      - postgres
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres-data:
