apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: restorejobs.operator.yugabyte.io
spec:
  group: operator.yugabyte.io
  scope: Namespaced
  names:
    plural: restorejobs
    singular: restorejob
    kind: RestoreJob
    categories:
      - all
      - yugabyte
  versions:
    - name: v1alpha1
      subresources:
        status: {}
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          description: Custom resource definition for YugabyteDB restore job
          properties:
            status:
              type: object
              description: Restore job status for the restore job custom resource.
              properties:
                message:
                  description: String log message from restore job controller
                  type: string
                taskUUID:
                  description: >
                    Internal UUID of the task associated with
                    the restore job resource.
                  type: string
                resourceUUID:
                  description: Internal UUID of the restore operation.
                  type: string
            spec:
              type: object
              properties:
                actionType:
                  description: Type of action to be taken. Allowed values - RESTORE
                  type: string
                  enum:
                    - RESTORE
                universe:
                  description: >
                    Name of the universe for which restore is to be taken,
                    refers to a ybuniverse CR name.
                  type: string
                backup:
                  description: >
                    Name of the backup to be restored,
                    refers to a backup CR name.
                  type: string
                keyspace:
                  description: Name of the keyspace to be restored.
                  type: string
