name: Create Repository Dispatch
on:
  release:
    types:
      released
jobs:
  createRepositoryDispatch:
    runs-on: ubuntu-latest
    steps:

      - name: "Trigger Repository Dispatch - yugabyte/terraform-gcp-yugabyte"
        run: |
          curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Content-Type: application/json" https://api.github.com/repos/yugabyte/terraform-gcp-yugabyte/dispatches \
          --data '{"event_type": "build-on-release", "client_payload":
                   {"prerelease": "${{ github.event.release.prerelease }}",
                    "release": "${{github.event.release.tag_name}}" } }'

      - name: "Trigger Repository Dispatch - yugabyte/terraform-aws-yugabyte"
        run: |
          curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Content-Type: application/json" https://api.github.com/repos/yugabyte/terraform-aws-yugabyte/dispatches \
          --data '{"event_type": "build-on-release", "client_payload":
                   {"prerelease": "${{ github.event.release.prerelease }}",
                    "release": "${{github.event.release.tag_name}}" } }'

      - name: "Trigger Repository Dispatch - yugabyte/terraform-azure-yugabyte"
        run: |
          curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Content-Type: application/json" https://api.github.com/repos/yugabyte/terraform-azure-yugabyte/dispatches \
          --data '{"event_type": "build-on-release", "client_payload":
                   {"prerelease": "${{ github.event.release.prerelease }}",
                    "release": "${{github.event.release.tag_name}}" } }'

      - name: "Trigger Repository Dispatch - yugabyte/azure-resource-manager"
        run: |
          curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Content-Type: application/json" https://api.github.com/repos/yugabyte/azure-resource-manager/dispatches \
          --data '{"event_type": "build-on-release", "client_payload":
                   {"prerelease": "${{ github.event.release.prerelease }}",
                    "release": "${{github.event.release.tag_name}}" } }'

      - name: "Trigger Repository Dispatch - yugabyte/gcp-deployment-manager"
        run: |
          curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Content-Type: application/json" https://api.github.com/repos/yugabyte/gcp-deployment-manager/dispatches \
          --data '{"event_type": "build-on-release", "client_payload":
                   {"prerelease": "${{ github.event.release.prerelease }}",
                    "release": "${{github.event.release.tag_name}}" } }'

      - name: "Trigger Repository Dispatch - yugabyte/aws-cloudformation"
        run: |
          curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Content-Type: application/json" https://api.github.com/repos/yugabyte/aws-cloudformation/dispatches \
          --data '{"event_type": "build-on-release", "client_payload":
                   {"prerelease": "${{ github.event.release.prerelease }}",
                    "release": "${{github.event.release.tag_name}}" } }'

      - name: "Trigger Repository Dispatch - yugabyte/homebrew-tap"
        run: |
          curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Content-Type: application/json" https://api.github.com/repos/yugabyte/homebrew-tap/dispatches \
          --data '{"event_type": "update-on-release", "client_payload":
                   {"prerelease": "${{ github.event.release.prerelease }}",
                    "release": "${{github.event.release.tag_name}}" } }'

      - name: "Trigger Repository Dispatch - yugabyte/yugabyte-operator"
        run: |
          curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Content-Type: application/json" https://api.github.com/repos/yugabyte/yugabyte-operator/dispatches \
          --data '{"event_type": "update-on-release",  "client_payload":
                   {"prerelease": "${{ github.event.release.prerelease }}",
                    "release": "${{github.event.release.tag_name}}"  }}'
